f10DataApiUrl = "http://fund.eastmoney.com/f10/F10DataApi.aspx"
gl_all_info_table = "funds_info"
gl_index_info_table = "index_info"

column_name = "name"
column_code = "code"
column_table_history = "history_db_table"
column_buy_table = "buy_table"
column_sell_table = "sell_table"
column_cost_hold = "cost_hold"
column_portion_hold = "portion_hold"
column_averagae_price = "aver_price"

column_date = "date"
column_net_value = "net_value"
column_growth_rate = "growth_rate"

column_cost = "cost"
column_portion = "portion"
column_soldout = "soldout"

column_money_sold = "money_sold"
column_cost_sold = "cost_sold"
column_earned = "earned"
column_return_percentage = "return_percent"

column_open = "open"
column_high = "high"
column_close = "close"
column_low = "low"
column_volume = "volume"
column_amount = "amount"
column_price_change = "price_change"
column_p_change = "p_change"
column_ma5 = "ma5"
column_ma10 = "ma10"
column_ma20 = "ma20"
column_v_ma5 = "v_ma5"
column_v_ma10 = "v_ma10"
column_v_ma20 = "v_ma20"